import documentSample from "./document.pdf";

export const pdfData = [
	{
		title: "documentTitle01",
		description: "Hello world",
		uploadedOn: "July 23, 2023",
		uploadedBy: "Firstname Lastname",
		fileOrigName: "documentTitle01.pdf",
		fileType: "PDF",
		fileSize: "375 KB",
		dimensions: "1920 by 768 pixels",
		file: documentSample,
	},
	{
		title: "documentTitle02",
		description: "Hello world",
		uploadedOn: "July 23, 2023",
		uploadedBy: "Firstname Lastname",
		fileOrigName: "documentTitle02.pdf",
		fileType: "PDF",
		fileSize: "375 KB",
		dimensions: "1920 by 768 pixels",
		file: documentSample,
	},
	{
		title: "documentTitle01",
		description: "Hello world",
		uploadedOn: "July 23, 2023",
		uploadedBy: "Firstname Lastname",
		fileOrigName: "documentTitle01.pdf",
		fileType: "PDF",
		fileSize: "375 KB",
		dimensions: "1920 by 768 pixels",
		file: documentSample,
	},
	{
		title: "documentTitle01",
		description: "Hello world",
		uploadedOn: "July 23, 2023",
		uploadedBy: "Firstname Lastname",
		fileOrigName: "documentTitle01.pdf",
		fileType: "PDF",
		fileSize: "375 KB",
		dimensions: "1920 by 768 pixels",
		file: documentSample,
	},
];
